#   phonegap persistence
#
beef:
    module:
        Persistence:
            enable: true
            category: "Phonegap"
            name: "Persistence"
            description: "Insert the beef hook into phonegap's index.html (iphone only)"
            authors: ["mh"]
            target:
                working: ["All"]
