#   phonegap
#
beef:
    module:
        File_upload:
            enable: true
            category: "Phonegap"
            name: "Upload file"
            description: "Upload files from device to server of your choice"
            authors: ["mh"]
            target:
                working: ["All"]
