#   phonegap
#
beef:
    module:
        Detect:
            enable: true
            category: "Phonegap"
            name: "Detect phonegap"
            description: "Detects if phonegap api is present"
            authors: ["mh"]
            target:
                working: ["All"]
